# Generated by Django 4.2.2 on 2024-10-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_code_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='204167', max_length=6, verbose_name='Код верификации'),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
