# Generated by Django 4.2.2 on 2024-10-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_code_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='816547', max_length=6, verbose_name='Код верификации'),
        ),
    ]
