# Generated by Django 4.2.2 on 2024-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='483792', max_length=6, verbose_name='Код верификации'),
        ),
    ]
