# Generated by Django 4.2.2 on 2024-10-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидаемый'), ('approved', 'Одобренный'), ('rejected', 'Отклоненный')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
